VERSION 0.8

build:
    DO ../udcs/image+CENTOS7
    DO ../udcs+LABEL
    DO ../udcs/os/centos+UPGRADE
    DO ../udcs/os/centos+TIMEZONE
    DO ../udcs/os/centos+REMOVE_UNUSED_PKG
    DO ../udcs/os/centos+COMMON_PKG

    CMD ["/bin/bash"]

    SAVE IMAGE --push cuilan/centos7:latest

all:
    BUILD --platform=linux/amd64 +build
