VERSION 0.8

LABEL:
    COMMAND
    LABEL maintainer="cuilan <17746598041@163.com>"
    LABEL repository="https://github.com/cuilan/earthlybuild"
    LABEL description="Earthly Build"
    LABEL licenses="Apache-2.0"

BUILD_DATE:
    COMMAND
    FROM cuilan/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")

OS_ARCH:
    COMMAND
    FROM cuilan/osarch

    ARG OS_ARCH=$(osarch)

TINI:
    COMMAND
    ENV TINI_VERSION v0.19.0
    ENV TINI_DOWNLOAD_URL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-amd64

    RUN curl -sSL ${TINI_DOWNLOAD_URL} > /usr/bin/tini \
        && chmod +x /usr/bin/tini
