VERSION 0.7

build-python38:
    FROM cuilan/centos7:latest
    
    DO ../udcs/language/python+INSTALL_PYTHON3815
    DO ../udcs/language/python+PIP_PROXY

    ARG --required BUILD_DATE

    CMD ["/bin/bash"]

    SAVE IMAGE --push cuilan/python:38-centos7 cuilan/python:38-centos7-${BUILD_DATE}

all:
    FROM cuilan/alpine

    ARG BUILD_DATE=$(date "+%Y%m%d%H%M%S")

    BUILD --platform=linux/amd64 +build-python38 --BUILD_DATE=${BUILD_DATE}