name: cuilan/golang

on:
  #schedule:
    #- cron: 0 3 * * 1
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  golang:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: golang